### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by lwassink** [louisscruz/remark#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [Remark](https://github.com/louisscruz/remark) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

TypeError: Cannot read property 'toLowerCase' of undefined
    at /packages/Remark/lib/remark.js:36:38
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1059:20)
    at TextEditor.module.exports.TextEditor.saveAs (/app.asar/src/text-editor.js:919:26)
    at Pane.module.exports.Pane.saveItemAs (/app.asar/src/pane.js:781:16)
    at Pane.saveItemAs (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:765:21)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -0:26.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
git-time-machine 1.5.4 
language-jsx 0.1.1 
markdown-preview-plus 2.4.1 
minimap 4.26.8 
nuclide 0.205.0 
pretty-json 1.6.1 
qolor 0.4.1 
Remark 1.1.0 
terminal-plus 0.14.5 
vim-mode-plus 0.82.0 
wordcount 2.10.4 
```

**Comment by louisscruz** [comment]
Fixed with the latest release!
